name: hummingbird 
display_name: Hummingbird
version: 0.1.0
author:
  name: "PrestaShop Team"
  email: "pub@prestashop.com"
  url: "https://www.prestashop.com"

meta:
  compatibility:
      from: 1.7.0.0
      to: ~

  available_layouts:
    layout-full-width:
      name: Full Width
      description: No side columns, ideal for distraction-free pages such as product pages.
    layout-both-columns:
      name: Three Columns
      description: One large central column and 2 side columns.
    layout-left-column:
      name: Two Columns, small left column
      description: Two columns with a small left column
    layout-right-column:
      name: Two Columns, small right column
      description: Two columns with a small right column

assets:
  # If you're using this theme as child and you want to load
  # the parent theme assets, uncomment this line.
#  use_parent_assets: true

  # The following lines are showing how to load assets in your page
  # Uncomment and change value to start loading css or js files
  css:
    all:
      - id: mainmenu-style 
        path: assets/css/modules/mainmenu.css
      - id: emailsubscription-style
        path: assets/css/modules/emailsubscription.css
      - id: blockcart-style
        path: assets/css/modules/shoppingcart.css
      - id: customersignin-style
        path: assets/css/modules/customersignin.css
      - id: socialfollow-style
        path: assets/css/modules/social-follow.css
      - id: socialsharing-style
        path: assets/css/modules/social-sharing.css
      - id: featuredproduct-style
        path: assets/css/modules/featuredproduct.css
    product:
      - id: product-style
        path: assets/css/product-page.css
        media: all
      - id: listing-style
        path: assets/css/listing.css
        media: all
      - id: blockreassurance-style
        path: assets/css/blockreassurance.css
        media: all
    checkout:
      - id: checkout-style
        path: assets/css/checkout.css
        media: all
    order-confirmation:
      - id: checkout-style
        path: assets/css/checkout.css
        media: all
    cart:
      - id: checkout-style
        path: assets/css/checkout.css
        media: all
      - id: blockreassurance-style
        path: assets/css/blockreassurance.css
        media: all
    category:
      - id: category-style
        path: assets/css/category.css
      - id: listing-style
        path: assets/css/listing.css
        media: all
      - id: facetedsearch-style
        path: assets/css/modules/facetedsearch.css
    contact:
      - id: contactform-style
        path: assets/css/modules/contactform.css
      - id: contactinfo-style
        path: assets/css/modules/contactinfo.css
    prices-drop:
      - id: listing-style
        path: assets/css/listing.css
        media: all
      - id: facetedsearch-style
        path: assets/css/modules/facetedsearch.css
    new-products:
      - id: listing-style
        path: assets/css/listing.css
        media: all
      - id: facetedsearch-style
        path: assets/css/modules/facetedsearch.css
    best-sales:
      - id: listing-style
        path: assets/css/listing.css
        media: all
      - id: facetedsearch-style
        path: assets/css/modules/facetedsearch.css
    manufacturer:
      - id: listing-style
        path: assets/css/listing.css
        media: all
      - id: facetedsearch-style
        path: assets/css/modules/facetedsearch.css
    search:
      - id: listing-style
        path: assets/css/listing.css
        media: all
      - id: facetedsearch-style
        path: assets/css/modules/facetedsearch.css
    index:
      - id: listing-style
        path: assets/css/listing.css
        media: all
      - id: imageslider-style
        path: assets/css/modules/imageslider.css
      - id: customtext-style
        path: assets/css/modules/customtext.css
  js:
    all:
      - id: currencyselector-lib
        path: assets/js/ps_currencyselector.js
      - id: languageselector-lib
        path: assets/js/ps_languageselector.js
    cart:
      - id: cart-lib
        path: assets/js/cart.js
    product:
      - id: product-lib
        path: assets/js/product.js
    category:
      - id: facetedsearch-lib
        path: assets/js/modules/facetedsearch.js
    prices-drop:
      - id: facetedsearch-lib
        path: assets/js/modules/facetedsearch.js
    checkout:
      - id: cart-lib
        path: assets/js/cart.js
      - id: checkout-lib
        path: assets/js/checkout.js
    manufacturer:
      - id: facetedsearch-lib
        path: assets/js/modules/facetedsearch.js
    new-products:
      - id: facetedsearch-lib
        path: assets/js/modules/facetedsearch.js
    best-sales:
      - id: facetedsearch-lib
        path: assets/js/modules/facetedsearch.js
    search:
      - id: facetedsearch-lib
        path: assets/js/modules/facetedsearch.js


global_settings:
  configuration:
    PS_IMAGE_QUALITY: png
  modules:
   to_enable:
     - ps_linklist
  hooks:
    modules_to_hook:
      displayNav1:
        - ps_contactinfo
      displayNav2:
        - ps_languageselector
        - ps_currencyselector
        - ps_customersignin
        - ps_shoppingcart
      displayTop:
        - ps_mainmenu
        - ps_searchbar
      displayHome:
        - ps_imageslider
        - ps_customtext
        - ps_featuredproducts
        - ps_banner
        - ps_newproducts
        - ps_bestsellers
      displayFooterBefore:
        - ps_emailsubscription
        - ps_socialfollow
      displayFooter:
        - ps_linklist
        - ps_customeraccountlinks
        - ps_contactinfo
        - ~
      displayLeftColumn:
        - ps_categorytree
        - ps_facetedsearch
      displaySearch:
        - ps_searchbar
      displayProductAdditionalInfo:
        - ps_sharebuttons
      displayOrderConfirmation2:
        - ps_featuredproducts
      displayCrossSellingShoppingCart:
        - ps_featuredproducts

  image_types:
    cart_default:
      width: 125
      height: 125
      scope: [products]
    small_default:
      width: 98
      height: 98
      scope: [products, categories, manufacturers, suppliers]
    medium_default:
      width: 452
      height: 452
      scope: [products, manufacturers, suppliers]
    home_default:
      width: 250
      height: 250
      scope: [products]
    large_default:
      width: 800
      height: 800
      scope: [products, manufacturers, suppliers]
    category_default:
      width: 141
      height: 180
      scope: [categories]
    stores_default:
      width: 170
      height: 115
      scope: [stores]

theme_settings:
  rtl_generation: false
  default_layout: layout-full-width
  layouts:
    category: layout-left-column
    best-sales: layout-left-column
    new-products: layout-left-column
    prices-drop: layout-left-column
    contact: layout-left-column
